---
iosxe-1:
  hostname: sandbox-iosxe-latest-1.cisco.com
  connection_options:
    scrapli:
      platform: cisco_iosxe
      port: 22
      extras:
        ssh_config_file: false
        auth_strict_key: false
iosxe-2:
  hostname: 172.18.0.12
  connection_options:
    scrapli:
      platform: cisco_nxos
      port: 22
      extras:
        ssh_config_file: false
        auth_strict_key: false
